name: matchsstatsprc

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=nyauIJicAzn7po91&
      - POSTGRES_DB=matchsstatsprcdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
